/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mindovercnc_linuxcnc_HalComponent */

#ifndef _Included_com_mindovercnc_base_data_FloatHalPin
#define _Included_com_mindovercnc_base_data_FloatHalPin
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mindovercnc_linuxcnc_HalComponent
 * Method:    addPin
 * Signature: (Lcom/mindovercnc/base/data/HalPin;)I
 */
JNIEXPORT void JNICALL Java_com_mindovercnc_base_data_FloatHalPin_setPinValue
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_mindovercnc_linuxcnc_HalComponent
 * Method:    getPin
 * Signature: (Ljava/lang/String;)Lcom/mindovercnc/base/data/HalPin;
 */
JNIEXPORT jobject JNICALL Java_com_mindovercnc_base_data_FloatHalPin_refreshValue
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
